service: express-backend-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  timeout: 15
  region: us-east-1
  memorySize: 2048

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      MONGODB_URL: mongodb+srv://ffarraahh14499:Fa123456@cluster0.dw8vbja.mongodb.net/awsDB?retryWrites=true&w=majority
